export enum DomainEventType {
  // Inbound & Inventory Events
  INBOUND_CREATED = 'INBOUND_CREATED',
  INBOUND_CONFIRMED = 'INBOUND_CONFIRMED',
  GOODS_REGISTERED = 'GOODS_REGISTERED',
  GOODS_RECEIVED = 'GOODS_RECEIVED',
  GOODS_PUT_AWAY = 'GOODS_PUT_AWAY',
  GOODS_TRANSFERRED = 'GOODS_TRANSFERRED',
  INVENTORY_MUTATED = 'INVENTORY_MUTATED',

  // Delivery & Logistics Events
  ORDER_CREATED = 'ORDER_CREATED',
  DRIVER_ASSIGNED = 'DRIVER_ASSIGNED',
  DRIVER_CHANGED = 'DRIVER_CHANGED',
  DELIVERY_STATUS_CHANGED = 'DELIVERY_STATUS_CHANGED',
  DELIVERY_COMPLETED = 'DELIVERY_COMPLETED',
  DELIVERY_RECEIPT_CONFIRMED = 'DELIVERY_RECEIPT_CONFIRMED',
  ORDER_MESSAGE_CREATED = 'ORDER_MESSAGE_CREATED',

  // Warehouse & Capacity Events
  WAREHOUSE_CAPACITY_CHANGED = 'WAREHOUSE_CAPACITY_CHANGED',
  RENTAL_CAPACITY_CHANGED = 'RENTAL_CAPACITY_CHANGED',

  // Billing & Payment Events
  INVOICE_CREATED = 'INVOICE_CREATED',
  INVOICE_UPDATED = 'INVOICE_UPDATED',
  INVOICE_ISSUED = 'INVOICE_ISSUED',
  INVOICE_PAID = 'INVOICE_PAID',
  INVOICE_OVERDUE = 'INVOICE_OVERDUE',
  INVOICE_CANCELLED = 'INVOICE_CANCELLED',
  PAYMENT_CREATED = 'PAYMENT_CREATED',
  PAYMENT_SUBMITTED = 'PAYMENT_SUBMITTED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_VERIFIED = 'PAYMENT_VERIFIED',
  PAYMENT_APPROVED = 'PAYMENT_APPROVED',
  PAYMENT_REJECTED = 'PAYMENT_REJECTED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_CANCELLED = 'PAYMENT_CANCELLED',
  PAYMENT_STATUS_CHANGED = 'PAYMENT_STATUS_CHANGED',

  // System & Notification Events
  NOTIFICATION_CREATED = 'NOTIFICATION_CREATED',
}

export interface DomainEvent<T = any> {
  id: string;
  type: DomainEventType;
  payload: T;
  timestamp: string;
  targetCustomerId?: string;
  targetWarehouseId?: string;
  targetDriverId?: string;
  targetOrderId?: string;
  targetInvoiceId?: string;
  targetPaymentId?: string;
  targetRoles?: string[];
}
